### ISSUE TITLE
bug when starting yaml topology without defaults

### ISSUE THREAD

**Issue by italovalcy** [mininet-sec/mininet-sec#32]
```
Traceback: Traceback (most recent call last):,   File "/src/mnsec/bin/mnsec", line 424, in <module>,     MininetRunner(),   File "/src/mnsec/bin/mnsec", line 134, in __init__,     self.begin(),   File "/src/mnsec/bin/mnsec", line 381, in begin,     mn = Net( topo=topo,,          ^^^^^^^^^^^^^^^,   File "/src/mnsec/mnsec/net.py", line 129, in __init__,     kwargs["topo"] = self.buildTopoFromFile(topoFile),                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,   File "/src/mnsec/mnsec/net.py", line 154, in buildTopoFromFile,     cls = SWITCHES[sw_opts.get("kind", defaults.get("switches_kind", SWITCHDEF))],                    ^^^^^^^^^^^, AttributeError: 'NoneType' object has no attribute 'get', 
```

Topology:
```
name: dns lab custom topology
defaults:
  env:
    DEFENVVAR1: xpto
hosts:
  secflood:
    ip: 192.168.0.10/24
    defaultRoute: via 192.168.0.1
    kind: k8spod
    image: hackinsdn/secflood:latest
    publish: ["8443:443"]
    env:
    - name: SECFLOOD_INTF_INSIDE
      value: secflood-eth0
    - name: SECFLOOD_GW_INSIDE
      value: 192.168.0.1
    - name: SECFLOOD_INTF_OUTSIDE
      value: secflood-eth0
  h1:
    ip: 192.168.0.15/24
    defaultRoute: via 192.168.0.1
  srv1:
    ip: 192.168.0.20/24
    defaultRoute: via 192.168.0.1
  outside:
    ip: 203.0.113.1/24
    defaultRoute: via 203.0.113.200
  kytos:
    ip: null
    kind: k8spod
    image: "hackinsdn/kytos:allinone"
    args:
      - "-E"
    env:
      - name: "MONGO_USERNAME"
        value: "kytos"
      - name: "MONGO_PASSWORD"
        value: "kytos"
      - name: "MONGO_DBNAME"
        value: "kytos"
      - name: "MONGO_HOST_SEEDS"
        value: "127.0.0.1:27017"
    publish:
      - "6653:6653"
      - "8181:8181"
  fw0:
    rules_v4:
      filter:
        - ':INPUT DROP'
        - ':OUTPUT ACCEPT'
        - ':FORWARD DROP'
        - '-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT'
        - '-A INPUT -p icmp -j ACCEPT'
        - '-A INPUT -s 192.168.1.0/24 -p udp --dport 53 -j ACCEPT'
        - '-A INPUT -s 10.0.0.0/24 -p udp --dport 53 -j ACCEPT'
        - '-A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT'
        - '-A FORWARD -p icmp -j ACCEPT'
        - '-A FORWARD -s 192.168.1.0/24 -p tcp -m multiport --dports 80,443 -j ACCEPT'
        - '-A FORWARD -d 10.0.0.1 -p tcp -m multiport --dports 80,443 -j ACCEPT'
        - '-A FORWARD -d 10.0.0.2 -p tcp -m multiport --dports 25,143,110 -j ACCEPT'
        - '-A FORWARD -o fw0-eth99 -j ACCEPT'
      nat:
        - '-A POSTROUTING -o fw0-eth99 -j MASQUERADE'
    defaultRoute: via 172.31.99.254
switches:
  s1:
    kind: lxbr
  nettap1:
links:
  - node1: s1
    node2: secflood
  - node1: s1
    node2: srv1
  - node1: s1
    node2: h1
  - node1: s1
    node2: kytos
  - node1: nettap1
    node2: outside
  - node1: nettap1
    node2: fw0
    ipv4_node2: '203.0.113.200/24'
  - node1: s1
    node2: fw0
    ipv4_node2: '192.168.1.1/24'
```
