### ISSUE TITLE
Errors in loading topologies after updates

### ISSUE THREAD

**Issue by mayara-santos01** [mininet-sec/mininet-sec#51]
After some updates made in Mininet-Sec, some custom topologies that were not changed started to not load correctly due to some conflicts caused by the updates. The following contains the error message related to the issue.

```
root@mininet:/src/mnsec# mnsec --topofile /customTopology.yaml
/usr/local/bin/mnsec:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('mnsec==1.1.0')
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

TypeError: 'NoneType' object is not iterable
Traceback: Traceback (most recent call last):,   File "/src/mnsec/bin/mnsec", line 424, in <module>,     MininetRunner(),   File "/src/mnsec/bin/mnsec", line 134, in __init__,     self.begin(),   File "/src/mnsec/bin/mnsec", line 381, in begin,     mn = Net( topo=topo,,          ^^^^^^^^^^^^^^^,   File "/src/mnsec/mnsec/net.py", line 165, in __init__,     kwargs.update(self.processTopoSettings()), TypeError: 'NoneType' object is not iterable, 
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleaning up Kubernetes Pods
*** Cleaning up Linux bridges
brctl show | tail +2 | cut -f1
*** Cleaning up L2TP interfaces
ip l2tp show tunnel | egrep -o 'Tunnel [0-9]+' | cut -d ' ' -f2
*** Cleanup complete.
```

**Comment by mayara-santos01** [comment]
This the image developed previously:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: config-custom-topo-${pod_hash}
data:
customTopology.yaml: |-
name: dns lab custom topology
defaults:
env:
DEFENVVAR1: xpto
hosts:
secflood:
ip: 192.168.0.10/24
kind: k8spod
image: hackinsdn/secflood:latest
publish: ["8443:443"]
env:
- name: SECFLOOD_INTF_INSIDE
value: secflood-eth0
- name: SECFLOOD_GW_INSIDE
value: 192.168.0.1
- name: SECFLOOD_INTF_OUTSIDE
value: secflood-eth0
srv1:
ip: 192.168.0.15/24
switches:
s1:
kind: lxbr
links:
- node1: s1
node2: secflood
- node1: s1
node2: srv1
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: mininet-sec-${pod_hash}
labels:
app: mininet-sec-${pod_hash}
spec:
replicas: 1
selector:
matchLabels:
app: mininet-sec-${pod_hash}
template:
metadata:
name: mininet-sec-${pod_hash}
labels:
app: mininet-sec-${pod_hash}
annotations:
container.apparmor.security.beta.kubernetes.io/mininet-sec: unconfined
spec:
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/hostname
operator: In
values: ${allowed_nodes}
containers:
- name: mininet-sec
image: hackinsdn/mininet-sec:latest
imagePullPolicy: Always
ports:
- containerPort: 8050
- containerPort: 8443
args: ["mnsec", "--topofile", "/customTopology.yaml"]
env:
- name: K8S_POD_HASH
value: ${pod_hash}
- name: K8S_NODE_AFFINITY
value: ${allowed_nodes_str}
- name: K8S_PROXY_CERT_FILE
value: /usr/local/etc/mnsec-proxy-ca.crt
- name: K8S_PROXY_HOST
value: mnsec-proxy-service.hackinsdn.svc.cnacv5
securityContext:
capabilities:
add: ["NET_ADMIN", "SYS_MODULE", "SYS_ADMIN"]
volumeMounts:
- name: lib-modules
mountPath: /lib/modules
- name: config-custom-topo-${pod_hash}-volume
readOnly: true
mountPath: "/customTopology.yaml"
subPath: "customTopology.yaml"
- name: mnsec-proxy-ca-volume
mountPath: /usr/local/etc/mnsec-proxy-ca.crt
readOnly: true
subPath: ca.crt
volumes:
- name: lib-modules
hostPath:
path: /lib/modules
type: Directory
- name: config-custom-topo-${pod_hash}-volume
configMap:
name: config-custom-topo-${pod_hash}
- name: mnsec-proxy-ca-volume
configMap:
defaultMode: 0600
name: mnsec-proxy-ca-configmap
---
apiVersion: v1
kind: Service
metadata:
name: mininet-sec-${pod_hash}
labels:
app: mininet-sec-${pod_hash}
spec:
type: NodePort
ports:
- port: 8050
targetPort: 8050
name: http-mininet-sec
- port: 8443
targetPort: 8443
name: https-secflood
selector:
app: mininet-sec-${pod_hash}
```
